### ISSUE TITLE
Don't log event.source - that raises the DOM Exception

### ISSUE THREAD

**Issue by aravindbaskaran** [kavithaiii/dashboard-container#1]
https://github.com/kavithaiii/dashboard-container/blob/f978666070a970d83518a5f8d1794f475e350e56/applicationB/public/page.html#L15-L16

Removing it works as expected. No extra headers, sandbox, etc. required

**Comment by kavithaiii** [comment]
@aravindbaskaran, have removed the `event.source` and removed **sandbox** attribute in iframe too.
Same error,
`Uncaught DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame.
    at http://localhost:8080/page.html:17:16`
